# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/semantic_joins',
                'doc_host': 'https://c-a-s-t-l-e.github.io',
                'git_url': 'https://github.com/c-a-s-t-l-e/semantic_joins',
                'lib_path': 'semantic_joins'},
  'syms': {'semantic_joins.core': {'semantic_joins.core.foo': ('core.html#foo', 'semantic_joins/core.py')}}}
